RUN apt-get update
RUN apt-get install build-essential
RUN apt-get install libevent-dev
RUN apt-get install libev-dev
RUN apt-get install libuv1-dev
RUN apt-get install libboost-all-dev

username=$(docker info | sed '/Username:/!d;s/.* //'); 


RUN mkdir /home/box
RUN chown -R $username:$username /home/box 